# Generated by Django 2.2.24 on 2023-01-12 21:00

from django.db import migrations
import phonenumbers as pn


def normalize_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        phone = pn.parse(flat.owners_phonenumber, 'RU')
        if pn.is_valid_number(phone) and pn.is_possible_number(phone):
            flat.owner_pure_phone = pn.format_number(phone,pn.PhoneNumberFormat.INTERNATIONAL)
        else:
            flat.owner_pure_phone = None
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20230113_0232'),
    ]

    operations = [
        migrations.RunPython(normalize_phone),
    ]
