# Generated by Django 2.2.24 on 2023-01-13 10:56

from django.db import migrations


def CopyflatDataToOwner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        owner, _ = Owner.objects.get_or_create(
            name=flat.owner,
            defaults={
                'owners_phonenumber':flat.owners_phonenumber,
                'owner_pure_phone': flat.owner_pure_phone
            }
        )
        owner.flats.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20230113_1655'),
    ]

    operations = [
        migrations.RunPython(CopyflatDataToOwner),
    ]
